#!/bin/bash
set -u

main () {
  cd $(cd $(dirname $0) && pwd)

  slug="$1"
  file_name="post/$(date +"%Y-%m-%d")-${slug}.md"
  file_path="content/$file_name"
  if [ ! -e "$file_path" ]; then
    hugo new "$file_name"
    sed -i '' 's/title = \".*\"/title = \"\"/g' "$file_path"
    sed -i '' "s/slug = \".*\"/slug = \"$slug\"/g" "$file_path"
  else
    echo "$file_name already exists."
  fi

  vim "$file_path"

}

main "$@"

